
services:

  pg_database:
   image: postgres:15-alpine
   ports:
     - "5439:5432" 
   restart: always
   volumes:
     - pgdata:/var/lib/postgresql/data
   env_file:
     - '.env'
   logging:
     driver: "json-file"
     options:
       max-size: "200k"
       max-file: "10"
      
  
  api:
    image: "receipts-api"
    stop_signal: SIGINT
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    env_file:
      - ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


volumes:
  pgdata: