"""move comment to receipt

Revision ID: 00c662a08d7a
Revises: 7e3ee62e98e6
Create Date: 2024-05-01 15:22:34.619576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c662a08d7a'
down_revision: Union[str, None] = '7e3ee62e98e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiptitems', 'comment')
    op.add_column('receipts', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'comment')
    op.add_column('receiptitems', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
